name: Release on main

permissions:
  contents: write

env:
  CHANGELOG_FILE: CHANGELOG.md

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest changelog entry
        id: changelog
        run: |
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
          
          # Get version from first 10 lines only
          VERSION=$(head -10 "$CHANGELOG_FILE" | grep -m1 '^## ' | sed -E 's/^## \[([0-9.]+)\].*/v\1/')
          
          # Get changelog body, limiting to reasonable size and escaping special chars
          BODY=$(awk '/^## /{i++}i==2{exit}i==1' "$CHANGELOG_FILE" | tail -n +2 | head -100)
          
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          
          # Use printf to safely handle special characters
          printf 'body<<EOF\n%s\nEOF\n' "$BODY" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.changelog.outputs.version }} \
            --title "Release ${{ steps.changelog.outputs.version }}" \
            --notes "${{ steps.changelog.outputs.body }}"